In [141]:
# So I have used SVM and Logistic Regression to build the model, I first took the answer column as input converted the yes, no values to a number
# then I split the dataset into the default 30% partition, using LogisticRegression and SVC I fit the model and used the respective parameters
# of the algorithms, as you can see that the data set is very imbalanced, hence the low accuracy.

In [72]:
import pandas as pd
import sklearn
# Importing Dataset
df = pd.read_csv('/content/drive/MyDrive/CodingClub-Machine Learning/task2.csv')
df

ID Segment type  ... Percentage It became a relationship
0     292890.8970          web  ...   0.000000                        0
1     292887.9870          web  ...   0.000000                        0
2     292894.0656       gender  ...   0.225255                        0
3     292887.1180          web  ...   0.000000                        0
4     292893.6561       gender  ...   0.211360                        0
...           ...          ...  ...        ...                      ...
1891  292887.5496          web  ...   0.000000                        0
1892  292881.6932       mobile  ...   0.312360                        0
1893  292900.8499       gender  ...   0.488025                        0
1894  292893.8600       gender  ...   0.488984                        0
1895  292890.2944          web  ...   0.000000                        0

[1896 rows x 7 columns]

In [73]:
df.fillna(0)
df

ID Segment type  ... Percentage It became a relationship
0     292890.8970          web  ...   0.000000                        0
1     292887.9870          web  ...   0.000000                        0
2     292894.0656       gender  ...   0.225255                        0
3     292887.1180          web  ...   0.000000                        0
4     292893.6561       gender  ...   0.211360                        0
...           ...          ...  ...        ...                      ...
1891  292887.5496          web  ...   0.000000                        0
1892  292881.6932       mobile  ...   0.312360                        0
1893  292900.8499       gender  ...   0.488025                        0
1894  292893.8600       gender  ...   0.488984                        0
1895  292890.2944          web  ...   0.000000                        0

[1896 rows x 7 columns]

In [124]:
x = df.iloc[:,[3]].values
y = df.iloc[:,6].values
import numpy as np
x = np.where(x=='Yes', 1, x)
x = np.where(x=='No', 0, x)
x = np.where(x=='I don\'t use Tinder', 0.2, x)


In [125]:
x


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=object)

In [126]:
y


array([0, 0, 0, ..., 0, 0, 0])

In [127]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [128]:
x_train.shape

(1422, 1)

In [129]:
x_test.shape

(474, 1)

In [130]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(x_train, y_train)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.654000 using {'C': 100, 'penalty': 'l2', 'solver': 'newton-cg'}


In [131]:
y_pred = grid_result.predict(x_test)

In [132]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)*100

65.18987341772153

In [133]:
confusion_matrix(y_pred,y_test)

array([[290, 151],
       [ 14,  19]])

In [135]:
# Probabilty of the respective classes
y_prob_test = grid_result.predict_proba(x_test)
y_prob_test

array([[0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.46439574, 0.53560426],
       [0.63524282, 0.36475718],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.63524282, 0.36475718],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.46439574, 0.53560426],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.63524282, 0.36475718],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.67461519, 0.32538481],
       [0.46439574, 0.53560426],
       [0.67461519, 0.32538481],
       [0.46439574, 0.53560426],
       [0.

In [136]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

model = SVC()
param = {
    'kernel':['rbf'],
    'C':[10]
}

grid = GridSearchCV(model,param,cv=5)
grid.fit(x_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [10], 'kernel': ['rbf']}, pre_dispatch='2*n_jobs',
             refit=True, return_train_score=False, scoring=None, verbose=0)

In [137]:
y_pred = grid.predict(x_test)

In [138]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)

0.6518987341772152

In [139]:
confusion_matrix(y_pred,y_test)

array([[290, 151],
       [ 14,  19]])